import { useEffect, useState } from 'react';
import { api, handleApiError } from '@/lib/api';
import { Button } from '@/components/ui/Button';
import { Input, Select } from '@/components/ui/Input';
import { Card, CardContent } from '@/components/ui/Card';
import { toast } from 'sonner';
import type { User } from '@/types';
export function SettingsPage(){
 const [settings,setSettings]=useState({storeName:'',storeAddress:'',storePhone:'',storeEmail:'',currency:'PKR',taxRate:0,lowStockThreshold:10}),[users,setUsers]=useState<User[]>([]),[busy,setBusy]=useState(false),[ready,setReady]=useState(false);
 const [form,setForm]=useState({name:'',email:'',password:'',role:'STAFF'});
 useEffect(()=>{Promise.all([api.get('/settings'),api.get('/users')]).then(([s,u])=>{setSettings(s.data);setUsers(u.data.users);setReady(true);}).catch(e=>toast.error(handleApiError(e)));},[]);
 const save=async(e:React.FormEvent)=>{e.preventDefault();setBusy(true);try{await api.put('/settings',settings);localStorage.setItem('store-currency',settings.currency);toast.success('Store settings saved');}catch(e){toast.error(handleApiError(e));}finally{setBusy(false);}};
 const add=async(e:React.FormEvent)=>{e.preventDefault();setBusy(true);try{const r=await api.post('/users',form);setUsers([...users,r.data.user]);setForm({name:'',email:'',password:'',role:'STAFF'});toast.success('Account created');}catch(e){toast.error(handleApiError(e));}finally{setBusy(false);}};
 return <div className="space-y-6 max-w-4xl"><h1 className="text-2xl font-bold">Store settings & accounts</h1><Card><CardContent className="p-6"><form onSubmit={save} className="grid sm:grid-cols-2 gap-4">{(['storeName','storeAddress','storePhone','storeEmail'] as const).map(k=><Input key={k} label={{storeName:'Store name',storeAddress:'Address',storePhone:'Phone',storeEmail:'Email'}[k]} required={k==='storeName'} type={k==='storeEmail'?'email':'text'} value={settings[k]} onChange={e=>setSettings({...settings,[k]:e.target.value})}/>)}<Select label="Currency" value={settings.currency} onChange={e=>setSettings({...settings,currency:e.target.value})} options={['PKR','USD','EUR'].map(value=>({value,label:value}))}/><Input label="Tax rate (%)" required type="number" min="0" max="100" step="0.01" value={settings.taxRate} onChange={e=>setSettings({...settings,taxRate:Number(e.target.value)})}/><Input label="Default minimum stock" required type="number" min="0" value={settings.lowStockThreshold} onChange={e=>setSettings({...settings,lowStockThreshold:Number(e.target.value)})}/><div className="sm:col-span-2"><Button type="submit" disabled={!ready} isLoading={busy}>Save settings</Button></div></form></CardContent></Card><Card><CardContent className="p-6 space-y-4"><h2 className="font-bold">Create staff or administrator account</h2><form onSubmit={add} className="grid sm:grid-cols-2 gap-3"><Input label="Name" required value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/><Input label="Email" required type="email" value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/><Input label="Initial password" required type="password" minLength={8} value={form.password} onChange={e=>setForm({...form,password:e.target.value})}/><Select label="Role" value={form.role} onChange={e=>setForm({...form,role:e.target.value})} options={['STAFF','ADMIN','MANAGER'].map(value=>({value,label:value}))}/><Button type="submit" isLoading={busy}>Create account</Button></form><div className="divide-y">{users.map(u=><p className="py-3" key={u.id}>{u.name} · {u.email} <span className="font-semibold">{u.role}</span></p>)}</div></CardContent></Card></div>;
}
export function ActivityPage(){const [rows,setRows]=useState<{id:string;action:string;userName:string;createdAt:string}[]>([]),[search,setSearch]=useState(''),[error,setError]=useState('');useEffect(()=>{api.get('/activity',{params:{search}}).then(r=>{setRows(r.data.activities);setError('');}).catch(e=>setError(handleApiError(e)));},[search]);return <div className="space-y-5"><h1 className="text-2xl font-bold">Activity log</h1><Input label="Search actions" value={search} onChange={e=>setSearch(e.target.value)}/>{error&&<p role="alert">{error}</p>}<Card><CardContent className="p-5 divide-y">{rows.map(r=><div key={r.id} className="py-4"><p className="font-medium">{r.action}</p><p className="text-sm text-slate-500">{r.userName} · {new Date(r.createdAt).toLocaleString()}</p></div>)}{!rows.length&&<p>No recorded activity.</p>}</CardContent></Card></div>}
