import { useEffect, useState } from 'react';
import { api, handleApiError } from '@/lib/api';
import { Button } from '@/components/ui/Button';
import { Input, Select } from '@/components/ui/Input';
import { Card, CardContent } from '@/components/ui/Card';
import { ResponsiveContainer, BarChart, Bar, XAxis, YAxis, Tooltip, CartesianGrid } from 'recharts';
import { formatCurrency } from '@/utils/formatters';
import { exportExcel, exportPDF } from './exports';
import type { Product, Sale, Customer } from '@/types';
type Point={name:string;value:number};
interface Data {missingHistoricalCosts:number;summary:Record<string,number>;daily:Point[];monthly:Point[];categories:Point[];topProducts:{name:string;quantity:number;revenue:number}[];productSales:{name:string;quantity:number;revenue:number}[];sales?:Sale[];products?:Product[];customers?:(Customer&{totalSpending:number;purchases:number})[];purchases?:{invoiceNumber:string;supplierName:string;status:string;paymentStatus:string;totalAmount:number;purchaseDate:string}[]}
function Chart({title,data}:{title:string;data:Point[]}) {return <Card><CardContent className="p-5"><h2 className="font-semibold mb-5">{title}</h2>{data.length?<ResponsiveContainer width="100%" height={250}><BarChart data={data}><CartesianGrid strokeDasharray="3 3" vertical={false}/><XAxis dataKey="name" tick={{fontSize:10}}/><YAxis tick={{fontSize:10}}/><Tooltip/><Bar dataKey="value" fill="#4f46e5" radius={[4,4,0,0]}/></BarChart></ResponsiveContainer>:<p className="h-48 flex items-center justify-center text-slate-500">No sales in this period.</p>}</CardContent></Card>}
export function AnalyticsPage({report=false}:{report?:boolean}) {
 const [data,setData]=useState<Data|null>(null),[error,setError]=useState(''),[startDate,setStart]=useState(''),[endDate,setEnd]=useState(''),[period,setPeriod]=useState('all');
 useEffect(()=>{let live=true;api.get('/analytics',{params:{startDate,endDate}}).then(r=>{if(live){setData(r.data);setError('');}}).catch(e=>{if(live)setError(handleApiError(e));});return()=>{live=false;};},[startDate,endDate]);
 const preset=(v:string)=>{setPeriod(v);if(v==='all'){setStart('');setEnd('');return;}const now=new Date(), from=new Date(); if(v==='weekly')from.setUTCDate(now.getUTCDate()-6); if(v==='monthly')from.setUTCDate(1);setStart(from.toISOString().slice(0,10));setEnd(now.toISOString().slice(0,10));};
 const sales=(data?.sales||[]).map(s=>({Invoice:s.invoiceNumber,Date:s.createdAt.slice(0,10),Customer:s.customerName||'Walk-in',Subtotal:s.totalAmount,Discount:s.discount,Tax:s.taxAmount,Total:s.netAmount,Payment:s.paymentMethod}));
 return <div className="space-y-6"><div className="flex flex-wrap justify-between gap-4"><div><h1 className="text-2xl font-bold">{report?'Reports & analytics':'Business dashboard'}</h1><p className="text-slate-500">Sales, stock and business performance from your recorded transactions.</p></div><a href="/pos"><Button>Open POS</Button></a></div>
 <div className="flex flex-wrap gap-3 items-end"><Select label="Period" value={period} onChange={e=>preset(e.target.value)} options={['all','daily','weekly','monthly'].map(value=>({value,label:value==='all'?'All time':value}))}/><Input label="From" type="date" value={startDate} onChange={e=>{setStart(e.target.value);setPeriod('all');}}/><Input label="To" type="date" value={endDate} onChange={e=>{setEnd(e.target.value);setPeriod('all');}}/></div>
 {error&&<p role="alert" className="text-red-600">{error}</p>}{!data&&!error&&<p>Loading business data…</p>}
 {data&&<>{data.missingHistoricalCosts>0&&<p className="rounded-lg bg-amber-50 border border-amber-200 p-4 text-sm">Some legacy sales have no recorded cost. Profit is unavailable for this range. New sales retain their cost at checkout.</p>}<div className="grid grid-cols-2 lg:grid-cols-4 gap-4">{[['totalSales','Total sales'],['todaySales',"Today's sales"],['totalProducts','Products'],['lowStock','Low stock'],['totalCustomers','Customers'],['pendingOrders','Pending purchases'],['monthlyRevenue','This month'],['profit','Profit before tax']].map(([key,label])=><Card key={key}><CardContent className="p-5"><p className="text-sm text-slate-500">{label}</p><p className="text-2xl font-bold mt-2">{key==='profit'&&data.missingHistoricalCosts>0?'Unavailable':['todaySales','monthlyRevenue','profit'].includes(key)?formatCurrency(data.summary[key]):data.summary[key]}</p></CardContent></Card>)}</div><div className="grid lg:grid-cols-2 gap-5"><Chart title="Daily sales (including tax)" data={data.daily}/><Chart title="Monthly sales (including tax)" data={data.monthly}/><Chart title="Top-selling products · units" data={data.topProducts.map(p=>({name:p.name,value:p.quantity}))}/><Chart title="Revenue by category (excluding tax)" data={data.categories}/></div>
 {report&&<><Card><CardContent className="p-5 space-y-4"><h2 className="font-bold">Download reports</h2><p className="text-sm text-slate-500">Sales, customer spending and purchases use the selected date range. Inventory is the current stock snapshot.</p><div className="flex flex-wrap gap-3"><Button onClick={()=>exportExcel('Sales',sales)}>Sales Excel</Button><Button onClick={()=>exportPDF('Sales report',['Invoice','Date','Payment','Total'],sales.map(s=>[s.Invoice,s.Date,s.Payment,s.Total]))}>Sales PDF</Button><Button onClick={()=>exportExcel('Inventory',(data.products||[]).map(p=>({SKU:p.sku,Product:p.name,Category:p.category?.name,Stock:p.stockQuantity,Minimum:p.lowStockThreshold,Cost:p.costPrice,Price:p.price})))}>Inventory Excel</Button><Button onClick={()=>exportExcel('Customers',(data.customers||[]).map(c=>({Name:c.name,Email:c.email,Phone:c.phone,Purchases:c.purchases,Spending:c.totalSpending})))}>Customers Excel</Button><Button onClick={()=>exportExcel('Purchases',(data.purchases||[]).map(p=>({Invoice:p.invoiceNumber,Supplier:p.supplierName,Status:p.status,Payment:p.paymentStatus,Date:p.purchaseDate.slice(0,10),Total:p.totalAmount})))}>Purchases Excel</Button><Button onClick={()=>exportExcel('Product sales',data.productSales)}>Product sales Excel</Button><Button onClick={()=>exportPDF(`Business report ${startDate||'all time'} to ${endDate||'today'}`,['Metric','Value'],Object.entries(data.summary).map(([k,v])=>[k,k==="profit"&&data.missingHistoricalCosts>0?"Unavailable: legacy costs missing":v]))}>Business / profit PDF</Button></div></CardContent></Card><Card><CardContent className="p-5"><h2 className="font-bold mb-3">Sales in this period</h2><div className="overflow-x-auto"><table className="w-full text-sm text-left"><thead><tr>{['Invoice','Date','Customer','Payment','Total'].map(h=><th className="p-2" key={h}>{h}</th>)}</tr></thead><tbody>{sales.map(s=><tr className="border-t" key={s.Invoice}><td className="p-2">{s.Invoice}</td><td>{s.Date}</td><td>{s.Customer}</td><td>{s.Payment}</td><td>{formatCurrency(s.Total)}</td></tr>)}</tbody></table>{!sales.length&&<p className="py-5">No sales in this period.</p>}</div></CardContent></Card></>}
 </>}</div>;
}
