import { useEffect, useState } from 'react';
import { api, handleApiError } from '@/lib/api';
import { Button } from '@/components/ui/Button';
import { Input, Select } from '@/components/ui/Input';
import { Card, CardContent } from '@/components/ui/Card';
import { Modal } from '@/components/ui/Modal';
import { productApi, supplierApi } from '@/features/inventory/api';
import { formatCurrency } from '@/utils/formatters';
import type { Product, Supplier } from '@/types';
import { toast } from 'sonner';
import { exportExcel } from './exports';
interface Purchase { id: string; invoiceNumber: string; supplierName: string; status: string; paymentStatus: string; purchaseDate: string; totalAmount: number; items: { productName: string; quantity: number; unitCost: number; subtotal: number }[] }
export function PurchasesPage() {
 const [rows,setRows]=useState<Purchase[]>([]), [products,setProducts]=useState<Product[]>([]), [suppliers,setSuppliers]=useState<Supplier[]>([]);
 const [open,setOpen]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[search,setSearch]=useState(''),[status,setStatus]=useState(''),[paymentFilter,setPaymentFilter]=useState(''),[supplierFilter,setSupplierFilter]=useState(''),[startDate,setStart]=useState(''),[endDate,setEnd]=useState('');
 const [supplierId,setSupplier]=useState(''),[date,setDate]=useState(new Date().toISOString().slice(0,10)),[paymentStatus,setPayment]=useState('UNPAID');
 const [items,setItems]=useState([{productId:'',quantity:1,unitCost:0}]),[detail,setDetail]=useState<Purchase|null>(null);
 const load=()=>api.get('/purchases',{params:{search,status,paymentStatus:paymentFilter,supplierId:supplierFilter,startDate,endDate}}).then(r=>{setRows(r.data.purchases);setError('');}).catch(e=>setError(handleApiError(e)));
 useEffect(()=>{load();},[search,status,paymentFilter,supplierFilter,startDate,endDate]);
 useEffect(()=>{Promise.all([productApi.getAll({limit:10000}),supplierApi.getAll()]).then(([p,s])=>{setProducts(p.data);setSuppliers(s);}).catch(e=>setError(handleApiError(e)));},[]);
 const update=async(id:string,data:object)=>{setBusy(true);try{await api.put(`/purchases/${id}`,data);toast.success('Purchase updated');await load();setDetail(null);}catch(e){toast.error(handleApiError(e));}finally{setBusy(false);}};
 const save=async(e:React.FormEvent)=>{e.preventDefault();setBusy(true);try{await api.post('/purchases',{supplierId,purchaseDate:date,paymentStatus,items});setOpen(false);setItems([{productId:'',quantity:1,unitCost:0}]);toast.success('Purchase order created');await load();}catch(e){toast.error(handleApiError(e));}finally{setBusy(false);}};
 return <div className="space-y-6"><div className="flex flex-wrap justify-between gap-3"><div><h1 className="text-2xl font-bold">Purchases</h1><p className="text-slate-500">Order from suppliers, receive inventory and track payments.</p></div><div className="flex gap-2"><Button onClick={()=>exportExcel('Purchases',rows.map(({items,...r})=>({...r,items:items.map(i=>`${i.productName} × ${i.quantity}`).join(', ')})))}>Export Excel</Button><Button onClick={()=>setOpen(true)}>New purchase</Button></div></div>
 <div className="grid sm:grid-cols-3 lg:grid-cols-6 gap-3"><Input label="Search" value={search} onChange={e=>setSearch(e.target.value)}/><Select label="Status" value={status} onChange={e=>setStatus(e.target.value)} options={['','PENDING','RECEIVED','CANCELLED'].map(value=>({value,label:value||'All statuses'}))}/><Select label="Payment" value={paymentFilter} onChange={e=>setPaymentFilter(e.target.value)} options={['','UNPAID','PARTIAL','PAID'].map(value=>({value,label:value||'All payments'}))}/><Select label="Supplier" value={supplierFilter} onChange={e=>setSupplierFilter(e.target.value)} options={[{value:'',label:'All suppliers'},...suppliers.map(s=>({value:s.id,label:s.name}))]}/><Input label="From" type="date" value={startDate} onChange={e=>setStart(e.target.value)}/><Input label="To" type="date" value={endDate} onChange={e=>setEnd(e.target.value)}/></div>
 {error&&<p role="alert" className="text-red-600">{error}</p>}
 <Card><CardContent className="p-0 overflow-x-auto"><table className="w-full text-sm text-left"><thead><tr>{['Order','Supplier','Date','Total','Status','Payment',''].map(x=><th key={x} className="p-4">{x}</th>)}</tr></thead><tbody>{rows.map(p=><tr key={p.id} className="border-t"><td className="p-4 font-mono">{p.invoiceNumber}</td><td>{p.supplierName}</td><td>{p.purchaseDate.slice(0,10)}</td><td>{formatCurrency(p.totalAmount)}</td><td>{p.status}</td><td>{p.paymentStatus}</td><td><Button variant="ghost" onClick={()=>setDetail(p)}>Details</Button></td></tr>)}</tbody></table>{!rows.length&&<p className="p-10 text-center text-slate-500">No purchases match these filters.</p>}</CardContent></Card>
 <Modal isOpen={open} onClose={()=>setOpen(false)} title="New purchase order" size="xl"><form onSubmit={save} className="space-y-4"><div className="grid sm:grid-cols-3 gap-3"><Select label="Supplier" required value={supplierId} onChange={e=>setSupplier(e.target.value)} options={[{value:'',label:'Select supplier'},...suppliers.map(s=>({value:s.id,label:s.name}))]}/><Input label="Purchase date" required type="date" value={date} onChange={e=>setDate(e.target.value)}/><Select label="Payment status" value={paymentStatus} onChange={e=>setPayment(e.target.value)} options={['UNPAID','PARTIAL','PAID'].map(value=>({value,label:value}))}/></div>
 {items.map((i,k)=><div key={k} className="grid sm:grid-cols-4 gap-2 items-end"><Select label="Product" required value={i.productId} onChange={e=>setItems(items.map((x,j)=>j===k?{...x,productId:e.target.value,unitCost:products.find(p=>p.id===e.target.value)?.costPrice||0}:x))} options={[{value:'',label:'Select product'},...products.map(p=>({value:p.id,label:p.name}))]}/><Input label="Quantity" type="number" min="1" step="1" required value={i.quantity} onChange={e=>setItems(items.map((x,j)=>j===k?{...x,quantity:Number(e.target.value)}:x))}/><Input label="Unit cost" type="number" min="0" step="0.01" required value={i.unitCost} onChange={e=>setItems(items.map((x,j)=>j===k?{...x,unitCost:Number(e.target.value)}:x))}/><Button type="button" variant="outline" disabled={items.length===1} onClick={()=>setItems(items.filter((_,j)=>j!==k))}>Remove</Button></div>)}
 <Button type="button" variant="outline" onClick={()=>setItems([...items,{productId:'',quantity:1,unitCost:0}])}>Add product</Button><p className="font-bold">Total: {formatCurrency(items.reduce((n,i)=>n+i.quantity*i.unitCost,0))}</p><Button type="submit" isLoading={busy}>Create purchase</Button></form></Modal>
 <Modal isOpen={!!detail} onClose={()=>setDetail(null)} title={detail?.invoiceNumber||'Purchase'} size="lg">{detail&&<div className="space-y-4"><p>{detail.supplierName} · {detail.status}</p>{detail.items.map((i,k)=><p key={k}>{i.productName} × {i.quantity} @ {formatCurrency(i.unitCost)} = {formatCurrency(i.subtotal)}</p>)}<Select label="Payment status" value={detail.paymentStatus} disabled={busy} onChange={e=>update(detail.id,{paymentStatus:e.target.value})} options={['UNPAID','PARTIAL','PAID'].map(value=>({value,label:value}))}/>{detail.status==='PENDING'&&<div className="flex gap-3"><Button disabled={busy} onClick={()=>update(detail.id,{status:'RECEIVED'})}>Receive into stock</Button><Button variant="outline" disabled={busy} onClick={()=>update(detail.id,{status:'CANCELLED'})}>Cancel order</Button></div>}</div>}</Modal></div>;
}
