require('dotenv').config();
const assert = require('node:assert/strict');
const { randomUUID } = require('node:crypto');
const { chromium } = require(process.env.PLAYWRIGHT_MODULE || 'C:/Users/DELL/AppData/Local/ms-playwright-go/1.57.0/package');
const jwt = require('jsonwebtoken');
const bcrypt = require('bcryptjs');
const { prisma } = require('../config/db');
const app = require('../index');
const auth = require('../services/auth.service');
const origin = process.env.TEST_FRONTEND_URL || 'http://127.0.0.1:5173';
(async () => {
 let browser, server; const ids = [];
 try {
  server = app.listen(0, '127.0.0.1');
  await new Promise(resolve => server.once('listening', resolve));
  const api = `http://127.0.0.1:${server.address().port}`;
  const password = 'AuthTest123!';
  const user = await prisma.user.create({data:{name:'Auth verification', email:`auth-${randomUUID()}@example.test`, role:'ADMIN', passwordHash:await bcrypt.hash(password,4)}}); ids.push(user.id);
  const session = await auth.loginUser(user.email, password);
  browser = await chromium.launch({channel:'chrome',headless:true});
  const page = await browser.newPage();
  let refreshes = 0;
  let failProfile = false;
  let refreshDelay = 0;
  const rejectNext = new Set();
  await page.route('**/api/**', async route => {
   const path = new URL(route.request().url()).pathname;
   if (rejectNext.delete(path)) return route.fulfill({status:401,contentType:'application/json',body:JSON.stringify({message:'Expired access token'})});
   if (path === '/api/auth/profile' && failProfile) return route.fulfill({status:503,contentType:'application/json',body:JSON.stringify({message:'Temporary verification outage'})});
   if (path === '/api/auth/refresh') {refreshes++;if(refreshDelay)await new Promise(resolve=>setTimeout(resolve,refreshDelay));}
   try {
    const response = await route.fetch({url:api + path + new URL(route.request().url()).search});
    await route.fulfill({response});
   } catch { await route.abort().catch(()=>{}); }
  });
  await page.goto(origin+'/login');
  await page.getByLabel('Email address',{exact:true}).fill(user.email);
  await page.getByLabel('Password',{exact:true}).fill('wrong-password');
  await page.locator('form').getByRole('button',{name:/sign in/i}).click();
  await page.getByRole('alert').filter({hasText:'Invalid email or password'}).waitFor();
  assert.ok(page.url().endsWith('/login'));
  await page.getByRole('tab',{name:'User',exact:true}).click();
  await page.getByLabel('Password',{exact:true}).fill(password);
  await page.locator('form').getByRole('button',{name:/sign in/i}).click();
  await page.getByRole('heading',{name:'Business dashboard',exact:true}).waitFor();
  assert.equal(await page.evaluate(()=>JSON.parse(localStorage.getItem('auth-storage')).state.user.role),'ADMIN');
  console.log('PASS wrong password rejected; correct credentials accepted despite a different role tab.');
  const expired = jwt.sign({id:user.id,tokenType:'access'},process.env.JWT_SECRET,{expiresIn:-10});
  await page.evaluate(value=>localStorage.setItem('auth-storage',JSON.stringify({state:{...value,isAuthenticated:true},version:0})), {...session,accessToken:expired});
  await page.goto(origin+'/dashboard');
  await page.getByRole('heading',{name:'Business dashboard',exact:true}).waitFor({timeout:8000}).catch(()=>{throw Error(`Expired session failed: URL=${page.url()}, refresh requests=${refreshes}`);});
  assert.equal(refreshes,1,'Expired session must refresh exactly once');
  await page.reload();
  await page.getByRole('heading',{name:'Business dashboard',exact:true}).waitFor();
  console.log('PASS expired access token refreshes once; dashboard survives reload.');
  failProfile = true;
  await page.reload();
  await page.getByRole('alert').filter({hasText:'Temporary verification outage'}).waitFor();
  assert.ok(await page.evaluate(()=>!!JSON.parse(localStorage.getItem('auth-storage')).state.refreshToken));
  failProfile = false;
  await page.getByRole('button',{name:'Retry',exact:true}).click();
  await page.getByRole('heading',{name:'Business dashboard',exact:true}).waitFor();
  console.log('PASS temporary server failure preserves session and Retry succeeds.');
  const before = refreshes;
  refreshDelay = 200;
  rejectNext.add('/api/analytics'); rejectNext.add('/api/notifications');
  const retriedAnalytics = page.waitForResponse(r=>new URL(r.url()).pathname === '/api/analytics'&&r.status()===200);
  const retriedNotifications = page.waitForResponse(r=>new URL(r.url()).pathname === '/api/notifications'&&r.status()===200);
  await page.reload();
  await Promise.all([retriedAnalytics,retriedNotifications]);
  assert.equal(refreshes-before,1);
  await page.waitForLoadState('networkidle');
  console.log('PASS concurrent API failures share one token refresh.');
  refreshDelay = 600;
  rejectNext.add('/api/products');
  const refreshingRequest = page.waitForRequest(r=>r.url().endsWith('/auth/refresh'));
  await page.getByRole('link',{name:'Inventory',exact:true}).click();
  await refreshingRequest;
  await page.getByRole('button',{name:'Logout',exact:true}).click();
  await page.waitForURL('**/login');
  await page.waitForTimeout(900);
  assert.equal(await page.evaluate(()=>JSON.parse(localStorage.getItem('auth-storage')).state.accessToken),null);
  console.log('PASS logout during refresh does not restore the old session.');
  refreshDelay = 0;
  const staff = await prisma.user.create({data:{name:'Auth staff',email:`staff-${randomUUID()}@example.test`,role:'STAFF',passwordHash:await bcrypt.hash(password,4)}});ids.push(staff.id);
  await page.getByLabel('Email address',{exact:true}).fill(staff.email);
  await page.getByLabel('Password',{exact:true}).fill(password);
  await page.locator('form').getByRole('button',{name:/sign in/i}).click();
  await page.getByRole('heading',{name:'Business dashboard',exact:true}).waitFor();
  assert.equal(await page.evaluate(()=>JSON.parse(localStorage.getItem('auth-storage')).state.user.role),'STAFF');
  await page.goto(origin+'/settings');
  await page.waitForURL('**/dashboard');
  await page.waitForLoadState('networkidle');
  console.log('PASS staff login uses stored role and cannot open admin Settings.');
 } finally {
  if(browser) for(const context of browser.contexts()) for(const page of context.pages()) await page.unrouteAll({behavior:'wait'});
  await browser?.close();
  await prisma.user.deleteMany({where:{id:{in:ids}}}); await prisma.$disconnect();
  if(server)await new Promise(resolve=>server.close(resolve));
 }
})().catch(error=>{console.error(error.message);process.exitCode=1;});
